# Generated by Django 6.1.1 on 2026-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizza/', verbose_name='Ảnh'),
        ),
    ]
