# Generated by Django 6.1.1 on 2026-09-13 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaweb', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Thông tin tài khoản', 'verbose_name_plural': 'Thông tin tài khoản'},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_user_per_pizza',
        ),
        migrations.AddField(
            model_name='review',
            name='action_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần chỉnh sửa/xóa'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Đã xóa'),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pizzaweb.orderitem', verbose_name='Sản phẩm trong đơn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'order_item'), name='one_review_per_user_per_order_item'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='pizza',
        ),
    ]
